### ISSUE TITLE
SQ Login TImeout

### ISSUE THREAD

**Issue by Ferni7** [flightplan-tool/flightplan#29]
Trying to search SQ (0.3.28) and getting timeouts on login, it never succeeds, is this just me or an issue?

andrew@fp:~$ flightplan search -w SQ -f MEL -t SIN -c first -s 2018-12-06 -e 2018-12-31 -q 2 -h --force
flightplan search 0.3.28
Searching 26 days of award inventory: 12/06/2018 - 12/31/2018
[SQ] DEPARTURE [SIN -> MEL] - 2018-12-06 (2 Passengers)
[SQ] info Logging in...
[SQ] error Unexpected error occurred while searching!
{ TimeoutError: waiting for selector "#kfLoginPopup #membership-1" failed: timeout 30000ms exceeded
    at new WaitTask (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/FrameManager.js:991:28)
    at Frame._waitForSelectorOrXPath (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/FrameManager.js:882:12)
    at Frame.waitForSelector (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/FrameManager.js:836:17)
    at Frame.waitFor (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/FrameManager.js:821:19)
    at Page.waitFor (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/Page.js:1022:29)
    at module.exports.login (/usr/local/share/.config/yarn/global/node_modules/flightplan-tool/src/engines/sq/searcher.js:34:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) name: 'TimeoutError' }
[SQ] DEPARTURE [SIN -> MEL] - 2018-12-07 (2 Passengers)

**Comment by jd20** [comment]
Working for me, when I tried just now. Can you try without -h, and verify visually if the login page is loading or not?

**Comment by Ferni7** [comment]
This is on a headless linux box so i can't run it without -h ...

**Comment by jd20** [comment]
Ok, I'm seeing the same timeout error when I enable headless mode, for SQ only. It's likely that SQ has figured out a way to detect that you're using a headless browser (there's a few ways they can tell, though I've patched most of them), and is blocking you on the basis of that. I'll need to dig a bit deeper, to see what's going on.

**Comment by Ferni7** [comment]
Ok thanks for confirming :)
