### ISSUE TITLE
NH Search failing (again)

### ISSUE THREAD

**Issue by Ferni7** [flightplan-tool/flightplan#30]
Candrew@fp:~flightplan search -w NH -f BKK -t SYD -c first -s 2019-08-01 -q 2 -h --force
flightplan search 0.3.30
Searching 1 days of award inventory: 08/01/2019 - 08/01/2019
[NH] DEPARTURE [BKK -> SYD] - 2019-08-01 (2 Passengers)
[NH] info Logging in...
[NH] success Login succeeded
[NH] error Unexpected error occurred while parsing!
Error: Invalid award fare: undefined
    at new Award (/usr/local/share/.config/yarn/global/node_modules/flightplan-tool/src/Award.js:22:13)
    at Node.$.each (/usr/local/share/.config/yarn/global/node_modules/flightplan-tool/src/engines/nh/parser.js:80:23)
    at initialize.exports.each (/usr/local/share/.config/yarn/global/node_modules/cheerio/lib/api/traversing.js:300:24)
    at module.exports.parseFlights (/usr/local/share/.config/yarn/global/node_modules/flightplan-tool/src/engines/nh/parser.js:34:33)
    at module.exports.parse (/usr/local/share/.config/yarn/global/node_modules/flightplan-tool/src/engines/nh/parser.js:22:29)
    at Results._parseAwards (/usr/local/share/.config/yarn/global/node_modules/flightplan-tool/src/Results.js:249:20)
    at Results.get awards [as awards] (/usr/local/share/.config/yarn/global/node_modules/flightplan-tool/src/Results.js:221:12)
    at main (/usr/local/share/.config/yarn/global/node_modules/flightplan-tool/bin/cli-search.js:382:28)
    at <anonymous>
[NH] DEPARTURE [SYD -> BKK] - 2019-08-01 (2 Passengers)

^Candrew@fp:~$ flightplan search -w NH -f BKK -t SYD -c first -s 2019-02-06 -q 2 -h --force
flightplan search 0.3.30
Searching 1 days of award inventory: 02/06/2019 - 02/06/2019
[NH] DEPARTURE [BKK -> SYD] - 2019-02-06 (2 Passengers)
[NH] info Logging in...
[NH] success Login succeeded
[NH] DEPARTURE [SYD -> BKK] - 2019-02-06 (2 Passengers)
success Search complete!

**Comment by jd20** [comment]
Thanks for reporting, will take a look!

**Comment by jd20** [comment]
Not able to reproduce using the 2019-08-01 query above, does it happen for you on other dates still? Can you try with latest version (0.3.48) and see if issue is still reproducible?
