### ISSUE TITLE
CX parser failing on economy awards

### ISSUE THREAD

**Issue by kochiya2002** [flightplan-tool/flightplan#38]
error Unexpected error occurred while parsing!
Error: Conflicting cabin status: [object Object]
    at module.exports.availabilityMap (C:\Users\kitko\AppData\Roaming\npm\node_modules\flightplan-tool\src\engines\cx\parser.js:138:15)
    at flightData.map.f (C:\Users\kitko\AppData\Roaming\npm\node_modules\flightplan-tool\src\engines\cx\parser.js:51:33)
    at Array.map (<anonymous>)
    at module.exports.parse (C:\Users\kitko\AppData\Roaming\npm\node_modules\flightplan-tool\src\engines\cx\parser.js:47:32)
    at Results._parseAwards (C:\Users\kitko\AppData\Roaming\npm\node_modules\flightplan-tool\src\Results.js:247:20)
    at Results.get awards [as awards] (C:\Users\kitko\AppData\Roaming\npm\node_modules\flightplan-tool\src\Results.js:214:12)
    at main (C:\Users\kitko\AppData\Roaming\npm\node_modules\flightplan-tool\bin\cli-search.js:382:28)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by kochiya2002** [comment]
Below is the search information
From HKG to KIX
Cabin: economy
from 2019-08-06 to 2019-08-11

**Comment by jd20** [comment]
Thanks, I will take a look at this.

**Comment by kochiya2002** [comment]
Thanks

**Comment by jd20** [comment]
Fixed on 0.3.46.
