### ISSUE TITLE
Asiamiles waitlist

### ISSUE THREAD

**Issue by nidotech** [flightplan-tool/flightplan#5]
Looks like the parser doesn't work on 'waitlist awards', I got no data at the GUI which showing 0 awards.

PS C:\Users\xxxx\desktop\flightplan> flightplan stats
Opening database...
Analyzing search requests...
CX:
  HKG => KIX (economy, 1x): 5
  KIX => HKG (economy, 1x): 5

sqlite3:
sqlite> select * from awards_requests;
1|CX|HKG|KIX|2018-09-01||economy|1|data/CX-HKG-KIX-2018-09-01-1532934841579.html.gz|3|2018-07-30 07:15:06
2|CX|KIX|HKG|2018-09-01||economy|1|data/CX-KIX-HKG-2018-09-01-1532934841579.html.gz|3|2018-07-30 07:15:43
3|CX|HKG|KIX|2018-09-02||economy|1|data/CX-HKG-KIX-2018-09-02-1532934841579.html.gz|3|2018-07-30 07:16:22
4|CX|KIX|HKG|2018-09-02||economy|1|data/CX-KIX-HKG-2018-09-02-1532934841579.html.gz|3|2018-07-30 07:17:00
5|CX|HKG|KIX|2018-09-03||economy|1|data/CX-HKG-KIX-2018-09-03-1532934841579.html.gz|3|2018-07-30 07:17:37
6|CX|KIX|HKG|2018-09-03||economy|1|data/CX-KIX-HKG-2018-09-03-1532934841580.html.gz|3|2018-07-30 07:18:20
7|CX|HKG|KIX|2018-09-04||economy|1|data/CX-HKG-KIX-2018-09-04-1532934841580.html.gz|3|2018-07-30 07:19:00
8|CX|KIX|HKG|2018-09-04||economy|1|data/CX-KIX-HKG-2018-09-04-1532934841580.html.gz|3|2018-07-30 07:19:39
9|CX|HKG|KIX|2018-09-05||economy|1|data/CX-HKG-KIX-2018-09-05-1532934841580.html.gz|3|2018-07-30 07:20:19
10|CX|KIX|HKG|2018-09-05||economy|1|data/CX-KIX-HKG-2018-09-05-1532934841580.html.gz|3|2018-07-30 07:20:56

one of the jpg under "data/":
![cx-hkg-kix-2018-09-01-1532934841579](https://user-images.githubusercontent.com/23376023/43384830-bdc5075e-9411-11e8-986b-69d8eefc2b80.jpg)

**Comment by jd20** [comment]
I'm not able to reproduce, what was the output when you ran parse? Can you try "flightplan parse -v"? Here were the commands I ran:

```bash
❯ flightplan search -w CX -f HKG -t KIX -c economy -s 2018-09-01
Creating database...
Searching 1 days of award inventory: 09/01/2018 - 09/01/2018
CX: Logging in...
CX: Login success!
CX: Loading airports...
CX: Found 846 airports
CX: DEPARTURE [HKG -> KIX] - 09/01/2018 (1 Passenger)
Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/Users/jason/Code/flightplan/node_modules/puppeteer/lib/ElementHandle.js:95:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
CX: DEPARTURE [KIX -> HKG] - 09/01/2018 (1 Passenger)
Search complete!

❯ flightplan search -v
Opening database...
Clearing old awards...
Parsing search requests...
CX: DEPARTURE [KIX -> HKG] - 2018-09-01 (1 Passenger)
  [KIX -> HKG] - 2018-09-01 CX567 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-01 CX503 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-01 CX565 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-01 CX595 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-01 CX507 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-01 CX569 ((Unknown Aircraft)): YS@ Y1@ Y2@
Search requests processed: 1
Total awards found: 6
```

Then, after running the server / client, I can see those waitlisted awards:

<img width="1270" alt="screen shot 2018-07-30 at 3 15 22 pm" src="https://user-images.githubusercontent.com/17896438/43426763-b8d6a884-940b-11e8-8f23-f7959eb78bc6.png">

**Comment by nidotech** [comment]
Looks like the output is normal?
```
c:\Users\xxx\Desktop\flightplan>flightplan parse -v
Opening database...
Clearing old awards...
Parsing search requests...
CX: DEPARTURE [HKG -> KIX] - 2018-09-01 (1 Passenger)
  [HKG -> KIX] - 2018-09-01 CX566 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-01 CX594 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-01 CX564 ((Unknown Aircraft)): YS@ Y1+ Y2+
  [HKG -> KIX] - 2018-09-01 CX506 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-01 CX568 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-01 CX502 ((Unknown Aircraft)): YS@ Y1+ Y2+
CX: DEPARTURE [KIX -> HKG] - 2018-09-01 (1 Passenger)
  [KIX -> HKG] - 2018-09-01 CX567 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-01 CX503 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-01 CX565 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-01 CX595 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-01 CX507 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-01 CX569 ((Unknown Aircraft)): YS@ Y1@ Y2@
CX: DEPARTURE [HKG -> KIX] - 2018-09-02 (1 Passenger)
  [HKG -> KIX] - 2018-09-02 CX566 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-02 CX594 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-02 CX564 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-02 CX506 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-02 CX568 ((Unknown Aircraft)): YS+ Y1+ Y2+
  [HKG -> KIX] - 2018-09-02 CX502 ((Unknown Aircraft)): YS@ Y1@ Y2@
CX: DEPARTURE [KIX -> HKG] - 2018-09-02 (1 Passenger)
  [KIX -> HKG] - 2018-09-02 CX567 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-02 CX503 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-02 CX565 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-02 CX507 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-02 CX569 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-02 CX595 ((Unknown Aircraft)): YS@ Y1@ Y2@
CX: DEPARTURE [HKG -> KIX] - 2018-09-03 (1 Passenger)
  [HKG -> KIX] - 2018-09-03 CX566 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-03 CX564 ((Unknown Aircraft)): YS@ Y1+ Y2+
  [HKG -> KIX] - 2018-09-03 CX8540 ((Unknown Aircraft)): YS+ Y1+ Y2+
  [HKG -> KIX] - 2018-09-03 CX506 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-03 CX568 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-03 CX502 ((Unknown Aircraft)): YS@ Y1+ Y2+
CX: DEPARTURE [KIX -> HKG] - 2018-09-03 (1 Passenger)
  [KIX -> HKG] - 2018-09-03 CX567 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-03 CX503 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-03 CX565 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-03 CX507 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-03 CX595 ((Unknown Aircraft)): YS@ Y1@ Y2@
CX: DEPARTURE [HKG -> KIX] - 2018-09-04 (1 Passenger)
  [HKG -> KIX] - 2018-09-04 CX566 ((Unknown Aircraft)): YS+ Y1+ Y2+
  [HKG -> KIX] - 2018-09-04 CX564 ((Unknown Aircraft)): YS+ Y1+ Y2+
  [HKG -> KIX] - 2018-09-04 CX506 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-04 CX568 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-04 CX502 ((Unknown Aircraft)): YS@ Y1@ Y2@
CX: DEPARTURE [KIX -> HKG] - 2018-09-04 (1 Passenger)
  [KIX -> HKG] - 2018-09-04 CX567 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-04 CX503 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-04 CX565 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-04 CX507 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-04 CX569 ((Unknown Aircraft)): YS@ Y1@ Y2@
CX: DEPARTURE [HKG -> KIX] - 2018-09-05 (1 Passenger)
  [HKG -> KIX] - 2018-09-05 CX566 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-05 CX564 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-05 CX506 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [HKG -> KIX] - 2018-09-05 CX568 ((Unknown Aircraft)): YS@ Y1+ Y2+
  [HKG -> KIX] - 2018-09-05 CX502 ((Unknown Aircraft)): YS@ Y1@ Y2@
CX: DEPARTURE [KIX -> HKG] - 2018-09-05 (1 Passenger)
  [KIX -> HKG] - 2018-09-05 CX567 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-05 CX503 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-05 CX565 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-05 CX507 ((Unknown Aircraft)): YS@ Y1@ Y2@
  [KIX -> HKG] - 2018-09-05 CX569 ((Unknown Aircraft)): YS@ Y1@ Y2@
Search requests processed: 10
Total awards found: 55```

**Comment by jd20** [comment]
Yep, sounds like you're getting same thing I was (waitlist awards in economy). Now that you've run the parse command, they should appear in the GUI.

**Comment by nidotech** [comment]
no, there's no data in the UI.
![image](https://user-images.githubusercontent.com/23376023/43504081-89528f3a-9594-11e8-94fd-985206acb34c.png)

```
C:\Users\xxx\Desktop\flightplan>flightplan client
yarn run v1.9.2
warning ..\..\package.json: No license field
$ cd client && yarn start
warning ..\..\..\package.json: No license field
$ react-app-rewired start
Starting the development server...

Compiled successfully!

You can now view flightplan in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://192.168.100.75:3000/

Note that the development build is not optimized.
To create a production build, use yarn build.```

**Comment by jd20** [comment]
From the screenshot, you're searching SFO-HKG, but the route you searched is HKG-KIX. Also, be sure sure "flightplan server" is running too.

**Comment by nidotech** [comment]
ohhhh right, didn't notice that. Now it's working, thanks for help!.

**Comment by jd20** [comment]
👍
