### ISSUE TITLE
flightplan-tool install error, successful NPM&node

### ISSUE THREAD

**Issue by spacemanspiff33** [flightplan-tool/flightplan#56]
Ubuntu 18.04
Everything went perfect following the setup guide. Confirmed Node.js and NPM were installed successfully (node v10.16.3 and npm v6.9.0 returned in terminal)
When running the $ npm install --global flightplan-tool I get the following errors:

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/jd20/commander.js.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mikey/.npm/_logs/2019-08-17T04_34_03_494Z-debug.log

**Comment by jd20** [comment]
Do you have git installed? What does `git --version` return?

**Comment by spacemanspiff33** [comment]
did not have git installed. Complete n00b here so i apologize
I installed git and was able to install flightplan using the `yarn global add flightplan-tool`
However, when i type flightplan (or a command after) i get `flightplan: command not found`
Anything easy i might be missing?

**Comment by Timothy0927** [comment]
Hi Jason @jd20 , 

I regularly updated to the latest version and the Flightplan-tool is amazing as always.
Recently I uninstalled it for some searching issue, but unable to re-installed it, could you please take a look for me? Thank you

Current version: 
**MacOS Majave 10.14.6
Xcode: 10.3
node version/npm: v12.9.0
yarn --version: v1.17.3
git version 2.20.1 (Apple Git-117)
node-gyp@5.0.3**

I began with
`yarn global add flightplan-tool`

and then 
error /Users/LiuChengHsin/.config/yarn/global/node_modules/integer: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/LiuChengHsin/.config/yarn/global/node_modules/integer
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.9.0 | darwin | x64
gyp info find Python using Python version 2.7.10 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node/12.9.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/LiuChengHsin/.config/yarn/global/node_modules/integer/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/12.9.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/LiuChengHsin/Library/Caches/node-gyp/12.9.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/LiuChengHsin/Library/Caches/node-gyp/12.9.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/12.9.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/LiuChengHsin/Library/Caches/node-gyp/12.9.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/LiuChengHsin/.config/yarn/global/node_modules/integer',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/integer/src/integer.o
../src/integer.cpp:329:21: error: no matching constructor for initialization of 'v8::String::Value'
                v8::String::Value utf16(string);
                                  ^     ~~~~~~
/Users/LiuChengHsin/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3038:5: note: candidate constructor not viable: no known conversion from 'v8::Local<v8::String>' to 'const v8::String::Value' for 1st argument
    Value(const Value&) = delete;
    ^
/Users/LiuChengHsin/Library/Caches/node-gyp/12.9.0/include/node/v8.h:3031:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    Value(Isolate* isolate, Local<v8::Value> obj);
    ^
1 error generated.
make: *** [Release/obj.target/integer/src/integer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/12.9.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.9.0/bin/node" "/usr/local/Cellar/node/12.9.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/LiuChengHsin/.config/yarn/global/node_modules/integer
gyp ERR! node -v v12.9.0

What can the matter be? 

Thank you very much, I am grateful for your help

Sincerely, 

Timothy Liu
