### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by Adai5839** [flightplan-tool/flightplan#57]
Hi there, I was trying to install the package on a Ubuntu VM (18.04), and I was running into error code as followed. Would you please help to explain what is wrong and what should be fixed? Thank you so much

```
 /home/arant/.nvm/versions/node/v12.8.1/bin/flightplan -> /home/arant/.nvm/versions/node/v12.8.1/lib/node_modules/flightplan-tool/bin/cli.js

 integer@1.0.7 install /home/arant/.nvm/versions/node/v12.8.1/lib/node_modules/flightplan-tool/node_modules/integer
 node-gyp rebuild

make: Entering directory '/home/arant/.nvm/versions/node/v12.8.1/lib/node_modules/flightplan-tool/node_modules/integer/build'
  CXX(target) Release/obj.target/integer/src/integer.o
../src/integer.cpp: In static member function ‘static Result Integer::Cast(v8::Local<v8::String>, uint8_t)’:
../src/integer.cpp:329:33: error: no matching function for call to ‘v8::String::Value::Value(v8::Local<v8::String>&)’
   v8::String::Value utf16(string);
                                 ^
In file included from /home/arant/.cache/node-gyp/12.8.1/include/node/node.h:63:0,
                 from ../src/integer.hpp:3,
                 from ../src/integer.cpp:1:
/home/arant/.cache/node-gyp/12.8.1/include/node/v8.h:3025:5: note: candidate: v8::String::Value::Value(v8::Isolate*, v8::Local<v8::Value>)
     Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~
/home/arant/.cache/node-gyp/12.8.1/include/node/v8.h:3025:5: note:   candidate expects 2 arguments, 1 provided
integer.target.mk:112: recipe for target 'Release/obj.target/integer/src/integer.o' failed
make: *** [Release/obj.target/integer/src/integer.o] Error 1
make: Leaving directory '/home/arant/.nvm/versions/node/v12.8.1/lib/node_modules/flightplan-tool/node_modules/integer/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/arant/.nvm/versions/node/v12.8.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.0.0-25-generic
gyp ERR! command "/home/arant/.nvm/versions/node/v12.8.1/bin/node" "/home/arant/.nvm/versions/node/v12.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/arant/.nvm/versions/node/v12.8.1/lib/node_modules/flightplan-tool/node_modules/integer
gyp ERR! node -v v12.8.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the integer@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arant/.npm/_logs/2019-08-20T03_04_23_480Z-debug.log
```

FYI: What I have done (starting from a clean Ubuntu 18.04)
1. install curl by $sudo apt install curl
2. install python 2.7 (and the build tools) by $sudo apt install python2.7 python-pip
3. install git by $apt-get install git-core
4. install nvm by $curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
5. install node and npm by $nvm install node
6. tried to install the package by $npm install --global flightplan-tool

**Comment by Adai5839** [comment]
was able to install using yarn.
