### ISSUE TITLE
Error when installing flightplan

### ISSUE THREAD

**Issue by atzy1090** [flightplan-tool/flightplan#61]
Hi guys, would appreciate if someone can guide me. I have zero experience in coding and am trying to install flight plan, but i get the following errors.

MacBook-Pro-3:~ AnsonT$ npm install --global flightplan-tool
/usr/local/bin/flightplan -> /usr/local/lib/node_modules/flightplan-tool/bin/cli.js

> integer@1.0.7 install /usr/local/lib/node_modules/flightplan-tool/node_modules/integer
> node-gyp rebuild

  CXX(target) Release/obj.target/integer/src/integer.o
../src/integer.cpp:329:21: error: no matching constructor for initialization of
      'v8::String::Value'
                v8::String::Value utf16(string);
                                  ^     ~~~~~~
/Users/anson/Library/Caches/node-gyp/13.5.0/include/node/v8.h:3210:5: note: 
      candidate constructor not viable: no known conversion from
      'v8::Local<v8::String>' to 'const v8::String::Value' for 1st argument
    Value(const Value&) = delete;
    ^
/Users/anson/Library/Caches/node-gyp/13.5.0/include/node/v8.h:3203:5: note: 
      candidate constructor not viable: requires 2 arguments, but 1 was provided
    Value(Isolate* isolate, Local<v8::Value> obj);
    ^
1 error generated.
make: *** [Release/obj.target/integer/src/integer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/13.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/flightplan-tool/node_modules/integer
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the integer@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anson/.npm/_logs/2019-12-26T03_58_40_863Z-debug.log

**Comment by toddheslin** [comment]
Hey @atzy1090 looks like this repo doesn't support your version of node (13.5.0). It looks like you have installed using homebrew so this article should help you out.

https://apple.stackexchange.com/questions/171530/how-do-i-downgrade-node-or-install-a-specific-previous-version-using-homebrew

I just checked using node@12 and it also failed, which means **we need to target node@10**. Following the steps in that article:

`brew install node@10`

`brew unlink node`

`brew link node@10`

`brew link --force --overwrite node@10`

Also install `node-gyp` by typing: `npm install -g node-gyp@latest`

In the project repo, delete your `node_modules` folder and then reinstall everything again using `npm i`

I've tested this using `nvm` which manages versions of node for me. I haven't tested with Homebrew but it *should* work.

**Comment by toddheslin** [comment]
Sorry, one note - I realised you were trying to install it globally. Similar steps above but you don't need to delete the `node_modules` folder and reinstall everything. Just try installing as you did before `npm install --global flightplan-tool`

**Comment by tszumowski** [comment]
> Hey @atzy1090 looks like this repo doesn't support your version of node (13.5.0). It looks like you have installed using homebrew so this article should help you out.
> 
> https://apple.stackexchange.com/questions/171530/how-do-i-downgrade-node-or-install-a-specific-previous-version-using-homebrew
> 
> I just checked using node@12 and it also failed, which means **we need to target node@10**. Following the steps in that article:
> 
> `brew install node@10`
> 
> `brew unlink node`
> 
> `brew link node@10`
> 
> `brew link --force --overwrite node@10`
> 
> Also install `node-gyp` by typing: `npm install -g node-gyp@latest`
> 
> In the project repo, delete your `node_modules` folder and then reinstall everything again using `npm i`
> 
> I've tested this using `nvm` which manages versions of node for me. I haven't tested with Homebrew but it _should_ work.

Confirmed same issue and this re-install procedure works. Thank you!
